Add templates for different types of issues
CosmoStat/wf-psf pull request #109
Opened 2023-12-20 16:32 UTC by nadamoukaddem

solves #106 
Implement ISSUE_TEMPLATE in the .github directory and configure all templates for different reported issue types, following the examples from the shapepipe repository.

2024-01-04 10:45 UTC, jeipollack commented
I have another request. Could you add a `refactoring-request.md` template?

---
name: Code Refactoring
about: Request for refactoring or improving the codebase
title: "[REFACTOR] Brief Description of Refactoring/Improvement"
labels: refactor, enhancement
assignees: ''

---

**Description of Refactoring/Improvement**
Provide a clear and concise description of the codebase elements you'd like to refactor or improve.

**Goals and Objectives**
Outline the goals and objectives of the refactoring or improvement effort.

**Current Code Behavior**
Describe the current behavior of the code and any issues or challenges it presents.

**Proposed Changes**
Specify the changes you propose for the refactoring or improvement. Include code snippets if applicable.

**Expected Benefits**
Explain the expected benefits of the proposed changes, such as improved performance, readability, or maintainability.

**Dependencies**
List any dependencies or considerations related to other parts of the codebase.

**Testing Plan**
Provide a plan for testing the refactored or improved code.

**Additional Context**
Include any other relevant context or information related to the refactoring or improvement.

**Impact Assessment**
Briefly assess the impact of these changes on the overall codebase and project.

**Next Steps**
Outline the next steps or actions that need to be taken for the refactoring or improvement.


Thank you for starting this request to refactor or improve the code. We will review it and collaborate to enhance the codebase together! 🛠️

2024-01-04 11:29 UTC, jeipollack requested changes
Hi Nada, thanks for working on this task. I made suggestions to improve the templates.

2024-01-04 11:29 UTC, jeipollack commented on .github/ISSUE_TEMPLATE/bug_report.md
Thanks, Nada.  I know you modelled this off of the ShapePipe, but I was thinking it could be improved with using more of an formal and imperative tone. Could you replace the `bug_report.md` with what I have below? Thanks.

---
name: Bug report
about: Create a report to help us improve
title: "[BUG] Issue title"
labels: bug
assignees: ''

---

**Describe the Bug**
Please provide a clear and concise description of the type of bug.

**Steps to Reproduce**
Outline the steps to reproduce the behavior:

**Expected Behavior**
Clearly describe what you expected to happen.

**Screenshots**
If applicable, attach screenshots to help illustrate the problem.

**Your Setup**
- OS: [e.g., iOS]
- Browser: [e.g., Chrome, Safari]
- Version: [e.g., 22]

**Additional Context**
Include any other context about the problem here.

Thank you for your cooperation in providing this bug report. Your input is valuable in helping us improve our system.

2024-01-04 11:29 UTC, jeipollack commented on .github/ISSUE_TEMPLATE/feature_request.md
Similarly, can you update the feature_request.md with the text ?

---
name: Feature request
about: Suggest an idea for this project
title: "[NEW FEATURE] Feature Title"
labels: enhancement
assignees: ''

---

**Problem Description**
Provide a clear and concise description of the problem your feature request aims to address. For example, share any frustrations or challenges you've encountered.

**Proposed Solution**
Describe the solution you envision. Be clear and concise about what you would like to see implemented.

**Alternatives Considered**
Share any alternative solutions or features you've thought about. Provide a brief description of each alternative.

**Additional Context**
Include any extra context or relevant screenshots regarding your feature request.

Your insights and suggestions are highly valuable as we consider enhancing our project. Thank you for taking the time to contribute! 🚀

2024-01-04 11:29 UTC, jeipollack commented on .github/ISSUE_TEMPLATE/help-.md
Again I know this template follows the ShapePipe one, but I think it could be improved with a bit more structure to ensure that those seeking help provide sufficient information to allow a quicker and more effective response. 
Also, could you rename the file `help-wanted.md`?

---
name: Help Request
about: General help needed
title: "[HELP] Brief Description of Help Needed"
labels: help wanted
assignees: ''

---

**Description of Help Needed**
Please provide a brief description of the issue or question you need help with.

**Steps Taken**
Outline any steps you've already taken to address the problem.

**Relevant Information**
Include any additional information that might help us better understand and address your request.

**Your Setup**
- OS: [e.g., iOS]
- Browser: [e.g., Chrome, Safari]
- Version: [e.g., 22]

**Screenshots or Code Snippets (if applicable)**
Attach any relevant screenshots or code snippets to provide more context.

Thank you for reaching out! We'll do our best to assist you promptly. 🤝

2024-01-04 11:29 UTC, jeipollack commented on .github/ISSUE_TEMPLATE/installation-issue.md
Again modified to use the imperative tone, and added a section to gather error messages. That will help us to reproduce the error and determine the cause.

---
name: Installation Issue
about: Problem with package installation
title: "[INSTALL ISSUE] Brief Description of Installation Problem"
labels: install issue
assignees: ''

---

**Description of the Problem**
Provide a clear and concise description of the problem encountered during installation.

**Steps to Reproduce**
Outline the steps to reproduce the behavior.

**Screenshots (if applicable)**
Attach any screenshots to help explain your problem.

**Your Setup**
- OS: [e.g., iOS]
- Browser: [e.g., Chrome, Safari]
- Version: [e.g., 22]

**Error Messages (if any)**
Include any error messages you received during the installation process.

**Additional Context**
Add any other relevant context about the problem here.

Thank you for reporting the installation issue. We'll do our best to assist you in resolving it! 🛠️

2024-01-04 11:29 UTC, jeipollack commented on .github/ISSUE_TEMPLATE/package-management.md
I am confused by this template. I think the name Package Management is an error and it should be called Project Management.

Could you rename the file `project-management.md`?  and use the template below:

---
name: Project Management
about: Issues related to the overall management of the project
title: "[PROJECT] Brief Description of the Issue"
labels: project management
assignees: ''

---

**Description of the Issue**
Provide a clear and concise description of the project management issue.

**Goals and Objectives**
Outline the primary goals and objectives associated with this issue or project.

**Current Progress**
Describe the current progress of the project or any specific milestones achieved.

**Challenges and Risks**
Identify any challenges or risks that may impact the project timeline or success.

**Dependencies**
List any dependencies or external factors that the team needs to consider for successful project management.

**Team Collaboration**
Describe how the team is collaborating on this project, including communication channels and collaboration tools used.

**Next Steps**
Outline the next steps or actions that need to be taken to address the project management issue.

**Timeline and Milestones**
Provide information on the project timeline and key milestones.

**Additional Context**
Include any other relevant context or information related to the project management problem.

**Impact Assessment**
Briefly assess the impact of this issue on the overall project.

2024-01-04 13:01 UTC, nadamoukaddem commented on .github/ISSUE_TEMPLATE/bug_report.md
File updated ✅

2024-01-04 13:07 UTC, nadamoukaddem commented on .github/ISSUE_TEMPLATE/feature_request.md
File updated.

2024-01-04 13:26 UTC, nadamoukaddem commented on .github/ISSUE_TEMPLATE/help-.md
necessary changes made

2024-01-04 14:18 UTC, nadamoukaddem commented on .github/ISSUE_TEMPLATE/installation-issue.md
Done

2024-01-04 14:32 UTC, nadamoukaddem commented on .github/ISSUE_TEMPLATE/package-management.md
file renamed and updated  ✅

2024-01-04 17:31 UTC, nadamoukaddem commented
All requested changes made.

2024-01-08 12:33 UTC, jeipollack approved these changes
Thanks a lot. It all looks good.

2024-01-08 12:33 UTC, merged