Manual triggers for CI and CD
CosmoStat/wf-psf pull request #126
Opened 2024-03-04 13:34 UTC by jeipollack

This PR includes two manual trigger workflows for CI and CD, respectively.
For CI_manual, we include a Python version matrix for versions 3.9 and 3.10 compatible with the latest release of WF-PSF. Python versions 3.11 and 3.12 requires upgrades to WF-PSF TensorFlow and TensorFlow Add-on packages.
For CD.yml, we also bumped up the Python version to 3.10.11.

Due to CI failures with `pytest==8.1.x` (https://github.com/CosmoStat/wf-psf/issues/125) and deprecated pytest-plugins (https://github.com/CosmoStat/wf-psf/issues/118), I locked `pytest>=7.0.0,<8.1' and removed deprecated pytest-plugins.

Ran CI and CD tests in forked repo: https://github.com/jeipollack/wf-psf/actions

2024-03-04 16:43 UTC, jeipollack commented
@sfarrens I am ready for you to review this PR.

2024-03-05 13:19 UTC, sfarrens requested changes
Just one minor point to resolve

2024-03-05 13:19 UTC, sfarrens commented on .github/workflows/cd_manual.yml
> +           publish_dir: docs/build
We probably don't actually want to **deploy** any documentation for a manual trigger. You can build an **artefact** instead that can be saved for a fixed amount of time on the server.

2024-03-05 13:19 UTC, sfarrens commented on .github/workflows/cd_manual.yml
> +    name: Deploy API documentation
See below and re-name appropriately.

2024-03-06 10:46 UTC, jeipollack commented on .github/workflows/cd_manual.yml
> +           publish_dir: docs/build
Replaced with command to archive doc as artifact
Tested and found a bug in the documentation opened ticket. So, it works. :-)

2024-03-06 10:46 UTC, jeipollack commented on .github/workflows/cd_manual.yml
> +    name: Deploy API documentation
Changed the name to: Test API documentation build

2024-03-06 10:48 UTC, jeipollack commented
@sfarrens ready for you to re-review the latest changes.

2024-03-07 15:59 UTC, jeipollack commented
Hi Sam, I was wondering if we could redirect this PR to `main` branch instead of `develop` in order to make immediate use of the manual trigger workflows. let me know what you think.

2024-03-12 15:42 UTC, sfarrens approved these changes

2024-03-12 15:42 UTC, sfarrens commented
This PR can be merged now

2024-03-13 10:12 UTC, merged