Rename SimPSFToolkit.py module
CosmoStat/wf-psf pull request #128
Opened 2024-03-06 11:18 UTC by nadamoukaddem

solves #112 
Changes Made:

- Renamed `SimPSFToolkit.py` to`psf_simulator.py`

- Renamed the class to `PSFSimulator`

- Updated all package and class imports throughout the codebase

2024-03-06 11:22 UTC, jeipollack commented on docs/source/wf_psf.sims.SimPSFToolkit.rst
The module name is psf_simulator.

2024-03-06 11:24 UTC, jeipollack reviewed
I am checking the first few changes and noticed that you didn't change references and imports of the new module name: `psf_simulator` instead calling it PSFSimulator. PSFSimulator is the name of the class not the module. 

Can you please go through and make sure module imports, class imports and doc strings are correct?

2024-03-07 10:23 UTC, jeipollack requested changes
There are a few more changes to implement.

2024-03-07 10:23 UTC, jeipollack commented on src/wf_psf/psf_models/tf_psf_field.py
All of the doc strings in this module are incorrect (even the old version was wrong).

It should be `wf_psf.sims.psf_simulator.PSFSimulator`.  Do understand why?

2024-03-07 10:23 UTC, jeipollack commented on src/wf_psf/metrics/metrics.py
> +    simPSF_np = PSFSimulator(
This should be `psf_simulator.PSFSimulator`

2024-03-07 10:23 UTC, jeipollack commented on src/wf_psf/data/training_preprocessing.py
> +import wf_psf.sims.psf_simulator as psf_simulator
This module import is not used, so let's remove it.

2024-03-07 10:23 UTC, jeipollack commented on src/wf_psf/psf_models/psf_model_parametric.py
> +            ``simPSF_np = wf.PSFSimulator(...)``
change to: `wf_psf.sims.psf_simulator.PSFSimulator`

2024-03-07 10:23 UTC, jeipollack commented on src/wf_psf/psf_models/psf_model_semiparametric.py
> +            ``simPSF_np = wf.PSFSimulator(...)``
change to: `wf_psf.sims.psf_simulator.PSFSimulator`

2024-03-07 13:05 UTC, nadamoukaddem commented
> There are a few more changes to implement.

Is it better to make all changes in one commit, or to commit each file separately?

2024-03-07 13:33 UTC, jeipollack commented
If you're performing exactly the same change for several files you can do it in one commit.  If it's a different type of change then it should go in another commit.

Also, please be sure to review the Workflow which took effect especially when it comes to branch naming conventions.

2024-03-07 14:10 UTC, nadamoukaddem commented on src/wf_psf/psf_models/tf_psf_field.py
because we want to call the class that will give us wavefront information ?

2024-03-07 14:16 UTC, jeipollack commented on src/wf_psf/psf_models/tf_psf_field.py
I meant do you know what `wf_psf.sims.psf_simulator.PSFSimulator` this means?

2024-03-07 14:24 UTC, nadamoukaddem commented on src/wf_psf/psf_models/tf_psf_field.py
that we're accessing the`PSFSimulator` class.

2024-03-07 14:34 UTC, nadamoukaddem commented
Okay, thank you, Jennifer. 
I'll make sure to follow the branch naming conventions next time. The conventions include three cases: Feature, Bug, and Hotfix. For my case, it will be 'enhancement/issue-number/short-description'?

2024-03-07 14:47 UTC, jeipollack commented on src/wf_psf/psf_models/tf_psf_field.py
yes, but what is everything before it? 
How do you import something (e.g. class, function, variable) from one module into another?

2024-03-07 15:06 UTC, jeipollack commented
> Okay, thank you, Jennifer.
> I'll make sure to follow the branch naming conventions next time. The conventions include three cases: Feature, Bug, and Hotfix. For my case, it will be 'enhancement/issue-number/short-description'?

No, the names must be from the three categories.  Which one would it be then?

2024-03-07 15:10 UTC, nadamoukaddem commented on src/wf_psf/psf_models/tf_psf_field.py
`psf-simulator` is the module or submodule, `sims` is a module and `wf_psf` is the package

2024-03-07 15:21 UTC, nadamoukaddem commented
> > Okay, thank you, Jennifer.
> > I'll make sure to follow the branch naming conventions next time. The conventions include three cases: Feature, Bug, and Hotfix. For my case, it will be 'enhancement/issue-number/short-description'?
> 
> No, the names must be from the three categories. Which one would it be then?

It's not a new feature, so I would say it's more like a bug.

2024-03-07 15:23 UTC, jeipollack commented on src/wf_psf/psf_models/tf_psf_field.py
you have a typo: `psf_simulator` is a module.
`sims` is a (sub)-package
`wf_psf` is a package.

The import statement is an absolute import, where the full path has been specified.

2024-03-07 16:08 UTC, nadamoukaddem commented
> There are a few more changes to implement.

Changes have been implemented.

2024-03-07 16:15 UTC, jeipollack commented
Thanks for the update. Did you test with runs of training and metrics to ensure no breaking behaviour?

2024-03-07 16:25 UTC, nadamoukaddem commented
> Thanks for the update. Did you test with runs of training and metrics to ensure no breaking behaviour?

Yes, but there are tests that require a GPU and they are skipped.

2024-03-07 16:37 UTC, jeipollack commented
Not unit tests. I meant validation tests.

2024-03-08 13:31 UTC, nadamoukaddem commented
> Not unit tests. I meant validation tests. Launch a batch script and make sure everything runs with no errors.

Okay, I will try testing it with Google Colab because Feynman is undergoing maintenance.

2024-03-11 13:05 UTC, nadamoukaddem commented
> Not unit tests. I meant validation tests. Launch a batch script and make sure everything runs with no errors.

I tested the code with a few epochs and got the expected output without any errors.

2024-03-14 10:36 UTC, jeipollack commented
Can you share your validation reports?

2024-03-14 15:25 UTC, nadamoukaddem commented
[wf-psf_renameModule.log](https://github.com/CosmoStat/wf-psf/files/14604421/wf-psf_renameModule.log)

2024-03-18 09:46 UTC, jeipollack commented
You uploaded a single log file of a run. I want to make sure you understand what is meant by validation reports that should be provided.  Can you explain more what this run is? What are the outputs you expected?

2024-03-18 10:47 UTC, nadamoukaddem commented
> You uploaded a single log file of a run. I want to make sure you understand what is meant by validation reports that should be provided. Can you explain more what this run is? What are the outputs you expected?

After renaming the module, I ran WaveDiff. If everything is working correctly, the code should run without errors, and the metrics should have similar logical values as before renaming. The values in the log seem reasonable, but for full assurance, we should compare them to the log from before the renaming.

2024-03-18 10:58 UTC, jeipollack commented
Thanks for this answer. Just a clarification, if you are using the same random seed and configuration for before-the-changes and after-the-changes run the results should be **exact**, not similar.  If they are not exact, it is important to investigate why they are not the same.

2024-03-18 11:06 UTC, nadamoukaddem commented
Yes, by 'similar' I meant the same. As you mentioned, if we are using the same random seed. Thanks for the specifics.

2024-03-18 11:20 UTC, jeipollack commented
Similar /= Same. 

Are you going to correct your report, so it's clear which run is the `before-changes` and `after-changes` runs? If you don't or can't run the validation tests, then you need to do the two runs and provide the corresponding logs.

2024-03-18 12:21 UTC, nadamoukaddem commented
the log I provided is after-changes run

2024-03-18 14:13 UTC, jeipollack commented
It is difficult as a reviewer to read bits of information across multiple comments. According to the Pull Request template, provide a summary of your checks in your original post. It's possible to edit it.  Again provide a complete report of the validation tests.  

Send me a notification when you're done and ready for me to review the Pull Request.

2024-03-18 16:47 UTC, nadamoukaddem commented
[metrics_after_changes.log](https://github.com/CosmoStat/wf-psf/files/14639773/metrics_after_changes.log)
[metrics_before_changes.log](https://github.com/CosmoStat/wf-psf/files/14639774/metrics_before_changes.log)
Done.

2024-03-18 20:10 UTC, jeipollack commented on src/wf_psf/data/training_preprocessing.py
> +import wf_psf.sims.psf_simulator as psf_simulator
I stated two week ago that this module import is not used in this module. I asked you to remove it. You did not do yet.

2024-03-18 20:19 UTC, jeipollack approved these changes
Thanks for working on this.

2024-03-18 20:19 UTC, merged