Feature interp
CosmoStat/wf-psf pull request #35
Opened 2022-09-19 13:33 UTC by CentofantiEze

This branch introduces the SED interpolation feature. Latest modifications allows using directly the interpolation while optimising the model instead of having to create outside an interpolated SED dataset. 

It adds new click options:
- `interp_pts_per_bin` int in {0,1,2,3}. Number of points per bin to add during the interpolation process.
- `extrapolate` bool. Whether extrapolation is performed or not.  
- `SED_interp_kind` str in {'linear', 'cubic'}. Type of interpolation for the SED. 
- `n_bins_gt` int. Number of bins used for the ground truth poly PSF generation.

2022-09-19 19:43 UTC, tobias-liaudat commented on long-runs/README.md
> +- `--train_opt`, default=True, type: bool
When you use values like `True`, types like  `bool` or numbers `1e-8` they should be in the markdown code.

This applies to all the options. For example:
- `--train_opt`, default=`True`,  type: `bool`

2022-09-19 19:44 UTC, tobias-liaudat commented on long-runs/README.md
> +- `--train_opt`, default=True, type: bool
To do for all the other options

2022-09-19 19:47 UTC, tobias-liaudat commented on long-runs/train_eval_plot_script_click.py
> +    help="Option to get SR pixel PSF RMSE for each individual test star.")
Improve help description. It is not very clear what the option does

2022-09-19 19:51 UTC, tobias-liaudat commented on long-runs/train_eval_plot_script_click.py
> +from email.policy import default
Why do you need this?

2022-09-19 19:51 UTC, tobias-liaudat commented on wf_psf/SimPSFToolkit.py
> +from asyncio.constants import SENDFILE_FALLBACK_READBUFFER_SIZE
Why do you need this?

2022-09-19 19:51 UTC, tobias-liaudat commented on wf_psf/SimPSFToolkit.py
> +from os import WIFSTOPPED
Why do you need this?

2022-09-19 19:52 UTC, tobias-liaudat commented on wf_psf/SimPSFToolkit.py
> +        Noise standard deviation for every SED bin, as a proportion of bins value.
Maybe it is better to express it as the standard deviation of a multiplicative noise, instead of a proportion of bin value

2022-09-19 19:54 UTC, tobias-liaudat commented on wf_psf/SimPSFToolkit.py
> +        Number of points to interpolate in between SED values. It can be 0, 1 or 2.
If it can be `0`, `1` or `2`, the function should verify it is actually one of those numbers.

The numbers should go in markdown code like this:  `0`, `1` or `2`.

2022-09-20 08:36 UTC, tobias-liaudat commented on wf_psf/SimPSFToolkit.py
> +        Number of points to interpolate in between SED values. It can be 0, 1 or 2.
I just saw that you did it below :)

2022-09-20 08:50 UTC, CentofantiEze commented on long-runs/train_eval_plot_script_click.py
> +from email.policy import default
I don't think I added those lines, and if it was me, it was not on purpose. I guess I can remove them.

2022-09-20 09:03 UTC, CentofantiEze commented on long-runs/README.md
> +- `--train_opt`, default=True, type: bool
Done.

2022-09-20 09:07 UTC, CentofantiEze commented on long-runs/train_eval_plot_script_click.py
> +    help="Option to get SR pixel PSF RMSE for each individual test star.")
Done. New description: 

`Save RMS error for each super resolved PSF in the test dataset in addition to the mean across the FOV.`

2022-09-20 09:11 UTC, CentofantiEze commented on wf_psf/SimPSFToolkit.py
> +from os import WIFSTOPPED
Same as the previous imports. I'll delete this lines (they were probably added automatically by VScode for debugging or something like that).

2022-09-20 09:43 UTC, CentofantiEze commented on wf_psf/SimPSFToolkit.py
> +        Noise standard deviation for every SED bin, as a proportion of bins value.
Done.

2022-09-20 10:16 UTC, tobias-liaudat commented on wf_psf/SimPSFToolkit.py
> +            if lim_hi != lim_low:
Maybe I missed something, when would the lim_hi be equal to the lim_low?

2022-09-20 10:33 UTC, tobias-liaudat commented on wf_psf/script_utils.py
> +    if args['model'] == 'poly' and args['reset_dd_features'] and args['cycle_def'] != 'only-parametric':
`reset_dd_features ` is not present in the click script

2022-09-20 10:34 UTC, tobias-liaudat commented on wf_psf/script_utils.py
> +    if args['model'] == 'poly' and args['pretrained_model'] is not None:
`pretrained_model ` is not in the click script

2022-09-20 10:35 UTC, tobias-liaudat commented on wf_psf/script_utils.py
> +    if args['model'] == 'poly' and args['reset_dd_features'] and args['cycle_def'] != 'only-parametric':
Verify that all the dictionary keys are in the click script

2022-09-20 10:35 UTC, tobias-liaudat commented on wf_psf/script_utils.py
> +    if args['model'] == 'poly' and args['reset_dd_features'] and args['cycle_def'] != 'only-parametric':
If you're going to add them in a new click script with all the parameters, the new click script should be in this PR

2022-09-20 10:38 UTC, tobias-liaudat commented on wf_psf/script_utils.py
> +    elif args['saved_model_type'] == 'external':
`external` is not mentioned in the click help for `saved_model_type`

2022-09-20 10:39 UTC, tobias-liaudat commented on wf_psf/script_utils.py
> +    elif args['saved_model_type'] == 'external':
Add in the help and explain what it is

2022-09-20 10:43 UTC, tobias-liaudat commented on wf_psf/tf_psf_field.py
> +        Extract from the DD non-parametric learnt features what could be represented by the parametric model
Improve docstring

2022-09-20 10:44 UTC, tobias-liaudat commented on wf_psf/tf_psf_field.py
> +        #beta_tilde = np.pad(beta_tilde_inner, [(0, S_tilde.shape[0]-beta_tilde_inner.shape[0]), (0, S_tilde.shape[0]-beta_tilde_inner.shape[1])], mode='constant')
Do we need to keep this commented line of code for some reason or could we remove it?

2022-09-20 10:44 UTC, tobias-liaudat commented on wf_psf/tf_psf_field.py
> +        #S_mat_projected = tf.tensordot(beta[:,:self.n_zernikes],tf_zernike_cube, axes=[1,0])
Do we need to keep this commented line of code for some reason or could we remove it?

2022-09-20 10:45 UTC, tobias-liaudat commented on wf_psf/tf_psf_field.py
> +        # Project over first 15 Zernikes
over the first Nz Zernikes

2022-09-20 10:50 UTC, tobias-liaudat commented on wf_psf/utils.py
> +    return np.sum((tf.math.multiply(tf_z1,tf_z2) ).numpy())/(norm_factor)
Add a newline at the end of the file

2022-09-20 10:52 UTC, tobias-liaudat requested changes
Everything seems fine, only some minor modifs are requested.

The new click script needs to be in the PR.

Before merging we will make a code cleanup using yapf and the yapf config file that is in the repo.

2022-09-20 10:54 UTC, tobias-liaudat commented
Some lines in the `project_DD_features` are not very clear (both with double inline list comprehensions ), it would be better to make them simpler, but it is not at all required

2022-09-20 11:24 UTC, CentofantiEze commented on wf_psf/SimPSFToolkit.py
> +            if lim_hi != lim_low:
`lim_hi` and `lim_low` are obtained as the closest value in `SED[0]` (the 350 wavelengths) to a given new bin limit `lims[1]` or `lims[0]` respectively.  If the number of original bins is the same as the number of filtered bins both `lim_hi` and `lim_low` can be assigned to the same `SED[0]` lambda point. When this happens (when we don't want to filter the SED) the lower limit will take in account the whole bin so we don't have to add the upper limit contribution. 

![SED_binning_limits](https://user-images.githubusercontent.com/42658822/191245266-7dd98716-a1fe-4bae-b381-e0b231016a61.png)

2022-09-20 11:26 UTC, CentofantiEze commented on wf_psf/script_utils.py
> +    if args['model'] == 'poly' and args['reset_dd_features'] and args['cycle_def'] != 'only-parametric':
`reset_dd_features` was added recently to the click script alongside to other _Feature Projection_ parameters and options.

2022-09-20 11:27 UTC, CentofantiEze commented on wf_psf/script_utils.py
> +    if args['model'] == 'poly' and args['pretrained_model'] is not None:
Now it is. The most recent version of the click script is the `train_eval_plot_script_click_multi_cycle.py`.

2022-09-20 11:32 UTC, CentofantiEze commented on wf_psf/script_utils.py
> +    elif args['saved_model_type'] == 'external':
Done!

2022-09-20 12:33 UTC, CentofantiEze commented on wf_psf/tf_psf_field.py
> +        Extract from the DD non-parametric learnt features what could be represented by the parametric model
New docstring:

Project non-parametric wavefront onto first n_z Zernikes and transfer their parameters to the parametric model.

2022-09-20 12:35 UTC, CentofantiEze commented on wf_psf/tf_psf_field.py
> +        #beta_tilde = np.pad(beta_tilde_inner, [(0, S_tilde.shape[0]-beta_tilde_inner.shape[0]), (0, S_tilde.shape[0]-beta_tilde_inner.shape[1])], mode='constant')
Removed line.

2022-09-20 12:44 UTC, CentofantiEze commented on wf_psf/tf_psf_field.py
> +        # Project over first 15 Zernikes
Done.

2022-09-20 12:46 UTC, CentofantiEze commented on wf_psf/utils.py
> +    return np.sum((tf.math.multiply(tf_z1,tf_z2) ).numpy())/(norm_factor)
Done.

2022-09-20 21:06 UTC, tobias-liaudat commented on long-runs/README.md
> +### Feature: project parameters
You're missing here the new parameters for the projections. The ones you added to the new click script

2022-09-20 21:08 UTC, tobias-liaudat commented on wf_psf/SimPSFToolkit.py
> +            if lim_hi != lim_low:
It's more clear now, thanks :)

2022-09-20 21:10 UTC, tobias-liaudat commented on long-runs/train_eval_plot_script_click_multi_cycle.py
> +    help="Type of interpolation for the SED.")
Include the different interpolation options "linear" or "..."

2022-09-20 21:10 UTC, tobias-liaudat commented on long-runs/train_eval_plot_script_click_multi_cycle.py
> +    help="Type of interpolation for the SED.")
Or only linear if that is the case

2022-09-20 21:17 UTC, tobias-liaudat requested changes
Appart from the two minor comments:

Why do you need to include the datasets in the `data/output/` directory?

For example the `train_Euclid_res_40_...`

2022-09-21 09:12 UTC, CentofantiEze commented on long-runs/README.md
> +### Feature: project parameters
Done.

2022-09-21 09:12 UTC, CentofantiEze commented on long-runs/train_eval_plot_script_click_multi_cycle.py
> +    help="Type of interpolation for the SED.")
Done.

2022-09-21 10:30 UTC, tobias-liaudat reviewed
Looks nice :) only yapf styling is missing before merging

2022-09-21 11:23 UTC, tobias-liaudat commented
This PR resolves #25, resolves #28, resolves #29, resolves #31 .

2022-09-21 11:24 UTC, tobias-liaudat approved these changes
Good job

2022-09-21 11:24 UTC, merged