Feature refactor UI
CosmoStat/wf-psf pull request #53
Opened 2023-02-09 15:32 UTC by jeipollack

This PR features many changes which I subdivide into major and minor categories:

**Major**
- Added a `run.py` module to launch at execution which parses the command line arg specifying the name of the configuration file
- Added a `.env` script storing the environment variables required to be set at execution with the `dotenv` package method `load_dotenv`
- Provided an `.env.example` in the repo which the user should update with the appropriate paths to the directories `wf-psf` repo, the directory for training and test datasets, and the location of the output directory closes #51 
- Added a `io.py` module with methods to automatically make the `wf-outputs` file structure defined in [long-runs instructions](https://github.com/CosmoStat/wf-psf/tree/feature_refactor_ui/long-runs#output-folders)
- New UI interface applied for setting training parameters resolves issues #43 and #50 with a main `configs.yaml` file which should store individual `config` files: `training_config.yaml`, `eval_config.yaml` , `plotting_config.yaml` and a `logging.conf`.  Only the `training_config.yaml` and `logging.conf` have been written and used so far.
- Created the `training` package which should contain `train.py` module with a class `TrainingParamsHandler` for extracting the different parameter subsets for training, psf model, and datasets, and a `train` method which should do the training once the psf model, training and test datasets have been specified (TO DO)
- Created a `psf_model` package containing for now a `psf_model.py` module with a decorator `register_psf_class` wrapping each PSF model class.  At runtime, a dictionary called `PSF_CLASSES` will get loaded all psf_model classes with the key determined by according to the class attribute `ids` which stores the short model name of the class specified in the `training_config.yaml`.
- Moved zernikes methods from the `utils.py` module to a `zernikes.py` module

**Minor Changes**
- Reduced `script_utils.py` to only train the `poly` model.  Have not tested it. 
- Corrected minor typos in commented versions 
- Created a `metrics` package and moved the `metrics.py` module there.

2023-02-09 15:51 UTC, jeipollack commented
oops. I just remembered that I need to write a method to verify that the config parameters are correct.

2023-02-09 16:03 UTC, sfarrens commented
Thanks @jeipollack, I will start reviewing this tomorrow. :)

2023-02-10 09:58 UTC, jeipollack commented
Thanks, @sfarrens. I am reviewing myself, too! I see that I need to tidy up the `io.py` module. And, since the construction of the output file directory is automatic I was thinking to convert it to internal commands. If you have any thoughts on that, let me know. Thanks!

2023-02-10 13:26 UTC, sfarrens requested changes
First batch of comments. 🙂

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +"""
We should decide on a documentation standard so that we can keep everything consistent going forward. My preference is [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) and ensuring that everything passes [pydocstyle](https://www.pydocstyle.org/en/stable/) tests.

In summary, for modules, it would be something along the lines of:

```python
"""MODULE NAME.

A short summary of what the modules contains.

:Author: Author's name

"""
```

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +_chkp = "chkp"
What does `chkp` stand for? Perhaps you can user a richer variable name.

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +    """
Again, we should set a standard for the function docstrings. My personal preference for functions is shown below. In this particular case, it could be useful to have a "See Also" section for each of the called functions.

```python
"""Function name in words.

A more detailed description of what the function does.

Parameters
----------
arg1 : dtype
    Argument description

Returns
-------
dtype
    Returned object description

Raises
------
Exception type
    Reason for exception

See Also
--------
Function/method : reason for connection

Examples
--------
Testable usage example(s)

Notes
-----
Additional information, equations, paper citations, etc.

"""
```

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +def _make_chkp_dir():
Missing docstring.

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +                              _chkp)).mkdir(exist_ok=True)
I would propose we use [Black](https://black.readthedocs.io/en/stable/) to manage the Python style formatting. This can integrated into various text editors (such as [VS Code](https://code.visualstudio.com/)) or run manually in the terminal.

In any case, for long lines it is better format them as follows.
```python
my_long_list = [
    item1,
    item2,
    ...,
]

my_long_function_call(
    arg1,
    arg2,
    ...,
)

my_super_long_string = (
    "this goes on for quite a bit ... "
    + "... and keeps going ... "
    + "... and so on."
)

```

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +                              _plots)).mkdir(exist_ok=True)
This looks like the same function repeated over and over. If you are simply passing a different argument each time I think this can be greatly simplified.

e.g.
```python
def _make_dir(dir_name):
    pathlib.Path(os.path.join(_workdir, _wf_outputs, dir_name)).mkdir(exist_ok=True)

_make_dir(_chkp)
```

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +_plots = "plots"
Since most of these variables are only used once, you could probably just make a tuple of strings and pass and loop through them (see comment below about the function redundancy).

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +    pass
Is this for something that you are planning to implement later?

2023-02-10 13:26 UTC, sfarrens commented on wf_psf/io.py
> +_workdir = os.getenv('WORKDIR')
I think you need to explain to me why we need environment variables to be defined at all?

2023-02-10 13:26 UTC, sfarrens commented on long-runs/train_eval_plot_script_click.py
> +from wf_psf.io import make_wfpsf_file_struct
Is the idea here to keep the existing scripts in working order until you have built a more general UI?

2023-02-10 13:29 UTC, jeipollack commented on wf_psf/io.py
> +_chkp = "chkp"
`chkp` stands for checkpoint the original naming scheme defined by Tobias.  I could rename to simply to `checkpoint` it's not very long.

2023-02-13 09:49 UTC, jeipollack commented on wf_psf/io.py
> +"""
Hi @sfarrens, many thanks for these useful suggestions. I began the modifications of the modules adopting the `numpy` docstyle.  I've committed and pushed my changes for `io.py` module.  For the other modules, it's made me rethink and change some of the structure.

Currently, I am working on the `psf_models.py` module that's a combo of my new additions and old additions.  This module contains a specific psf model, which should go into its own module as with the other PSF models.  
I also started modifying the `training.py` module in the `training` package.  There also more steps to carry out here.

I want to check if it's okay with you if I carry on the development of these two packages, i.e. PSF models and Training, before resubmitting this PR. Or, do you prefer I focus on just the specific items raised in this PR concerning UI?

2023-02-13 09:58 UTC, jeipollack commented on wf_psf/io.py
> +                              _chkp)).mkdir(exist_ok=True)
Thanks for this tip.  I pip installed `Black` and installed the Black extension into VSCode, as well as updated my `settings.json` file

```
{
    "python.analysis.extraPaths": [
        "./wf_psf/training"
    ],
    "[python]": {
        "editor.defaultFormatter": null,
        "editor.insertSpaces": true,
        "editor.tabSize": 4,
        "editor.formatOnSave": true
    }
}
```

But, it doesn't automatically update upon saving.  I have to run Black manually from the command-line.  And, note I am not quite sure why I have listed `python.analysis.extraPaths` in the `settings.json`. I don't recall adding it there. :D I have to see what that does.

2023-02-13 09:58 UTC, jeipollack commented on wf_psf/io.py
> +_plots = "plots"
done!

2023-02-13 09:59 UTC, jeipollack commented on wf_psf/io.py
> +                              _plots)).mkdir(exist_ok=True)
done!

2023-02-13 10:00 UTC, jeipollack commented on wf_psf/io.py
> +def _make_chkp_dir():
I removed this function.

2023-02-13 10:01 UTC, jeipollack commented on wf_psf/io.py
> +    pass
Yes, it was added a reminder to match the original code.  But, I decided to remove it as the log file is created at the start of the program.

2023-02-13 10:09 UTC, jeipollack commented on long-runs/train_eval_plot_script_click.py
> +from wf_psf.io import make_wfpsf_file_struct
I forgot about this change. I think this particular method is not needed.  But, I wasn't planning to run the existing script in this branch as I trimmed it down. Now I am debating whether that is a bad idea.  I guess if I need to debug, I can bring back some of the older parts if I trimmed too much.

2023-02-13 11:08 UTC, jeipollack commented on wf_psf/io.py
> +_workdir = os.getenv('WORKDIR')
This `load_dotenv` is temporary.  Actually, I had initially coded this variable to be passed in as a command-line argument, but I changed to specifying environment variables so the user doesn't have to specify it for this specific program. I was thinking these variables would also be defined when running on different systems and in the Euclid interface scripts.

2023-02-14 14:14 UTC, sfarrens commented on wf_psf/io.py
> +        Lists of output directories
This is not technically a parameter because it is not passed as an argument to `_setup_dirs`

2023-02-14 14:14 UTC, sfarrens commented on wf_psf/io.py
> +        Log filename with absolute path
Same point here regarding parameters.

2023-02-14 14:14 UTC, sfarrens commented on wf_psf/io.py
> +_plots = "plots"
These three variables only appear to be called once. Is there a reason they need to be defined at the module level?

2023-02-14 14:14 UTC, sfarrens commented on wf_psf/io.py
> +"""IO
```suggestion
"""IO.
```

2023-02-14 14:15 UTC, sfarrens commented on wf_psf/io.py
> +"""
We can discuss this in our next meeting.

2023-02-14 14:16 UTC, sfarrens commented on wf_psf/io.py
> +_workdir = os.getenv('WORKDIR')
OK, my question is more basic. Why does the user need to specify a `WORKDIR` environment variable, rather than e.g. specifying a path in the config file?

2023-02-14 14:19 UTC, jeipollack commented on wf_psf/io.py
> +        Lists of output directories
Thanks, I was waiting for this comment bc I wasn't sure. :-)

2023-02-14 14:19 UTC, jeipollack commented on wf_psf/io.py
> +        Log filename with absolute path
same as above.

2023-02-14 14:27 UTC, jeipollack commented on wf_psf/io.py
> +_plots = "plots"
These are the equivalent of [L36 ](https://github.com/CosmoStat/wf-psf/blob/899a6e36502b8ddc7af99dce04c30019c653bcf8/wf_psf/script_utils.py#L36) in `script_utils.py` (although they are paths not files) and are used in the training, evaluating, and plotting methods.  I call them once in the module, but I was planning to call them again when creating and writing to file in their respective directories.

2023-02-14 14:28 UTC, jeipollack commented on wf_psf/io.py
> +"""IO
Thanks, I corrected in my local version, but didn't push. :-)

2023-02-14 14:40 UTC, jeipollack commented on wf_psf/io.py
> +_workdir = os.getenv('WORKDIR')
Initially,  I assumed the repository was in the path of the `WORKDIR`, because that is the case for me.  But, I decided it doesn't have to be if the user would prefer it be in a different location.  It could go into the config file. Is that what you prefer? :-)

2023-02-14 14:48 UTC, sfarrens commented on wf_psf/io.py
> +_workdir = os.getenv('WORKDIR')
My view is that things like environment variables are not as easily controlled by us (i.e. the developers). So, if someone has an issue e.g. because they manually set `WORKDIR` to something weird, it is hard for us to do anything about it. Of course the same could happen with a config file, but it is easier for us to identify the source of the issue.

2023-02-14 16:53 UTC, sfarrens commented on wf_psf/io.py
> +_plots = "plots"
OK, I think we can look at this during our next meeting also.

2023-02-15 11:50 UTC, jeipollack commented on wf_psf/io.py
> +_workdir = os.getenv('WORKDIR')
yes, that's a good point

2023-02-15 14:37 UTC, jeipollack commented on wf_psf/io.py
> +_plots = "plots"
I created a FileIOHandler class and moved these guys to attributes of this class.

2023-02-15 14:48 UTC, jeipollack commented on wf_psf/io.py
> +_workdir = os.getenv('WORKDIR')
I renamed this variable to `outputdir` and it's now a command-line arg / instance variable for the `class FileIOHandler`

2023-02-15 15:24 UTC, sfarrens requested changes

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/io.py
> +    _setup_dirs()
Remove

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/io.py
> +load_dotenv("./.env")
Remove

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/io.py
> +        repodir = os.getenv("REPODIR")
Change to config option

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/io.py
> +from dotenv import load_dotenv
Remove

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/run.py
> +"""WF_PSF Run
```suggestion
"""WF_PSF Run.
```

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/run.py
> +repodir = os.getenv("REPODIR")
Remove/update

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/run.py
> +configs = read_stream(os.path.join(repodir, args.conffile))
Update

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/run.py
> +        training_params = read_conf(os.path.join(repodir, conf.training_conf))
Update

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/run.py
> +from dotenv import load_dotenv
Remove

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/training/train.py
> +"""Train
```suggestion
"""Train.
```

2023-02-15 15:24 UTC, sfarrens commented on wf_psf/training/train.py
> +if __name__ == "__main__":
Remove

2023-02-15 16:24 UTC, sfarrens requested changes

2023-02-15 16:24 UTC, sfarrens commented on wf_psf/run.py
> +#!/usr/bin/env python
You should decide if you want this to be a script (at least for now) or not.

2023-02-15 16:24 UTC, sfarrens commented on wf_psf/training/train.py
> +        Dictionary storing optimiser parameters
Check, which parameters are actually being passed to `__init__`. Also no need for the `-` before each parameter name.

2023-02-15 16:24 UTC, sfarrens commented on wf_psf/training/train.py
> +        self.training_params = training_params.training
Maybe it would be easier to pass the `training_params.training` object directly to this class?

2023-02-15 16:24 UTC, sfarrens commented on wf_psf/training/train.py
> +    device_name
This should be a valid data type.

2023-02-15 16:24 UTC, sfarrens commented on wf_psf/training/train.py
> +    training_params: Recursive Namespace
I don't think this is a valid data type.

2023-02-15 16:24 UTC, sfarrens commented on wf_psf/training/train.py
> +    workdir = os.getenv("HOME")
Remove

2023-02-16 14:26 UTC, jeipollack commented on wf_psf/io.py
> +    _setup_dirs()
done.

2023-02-16 14:26 UTC, jeipollack commented on wf_psf/io.py
> +load_dotenv("./.env")
done.

2023-02-16 14:27 UTC, jeipollack commented on wf_psf/io.py
> +        repodir = os.getenv("REPODIR")
changed to command-line arg

2023-02-16 14:27 UTC, jeipollack commented on wf_psf/io.py
> +from dotenv import load_dotenv
done.

2023-02-16 15:22 UTC, jeipollack commented on wf_psf/run.py
> +#!/usr/bin/env python
rm. it is a script for now.

2023-02-16 15:22 UTC, jeipollack commented on wf_psf/run.py
> +from dotenv import load_dotenv
Done

2023-02-16 15:22 UTC, jeipollack commented on wf_psf/run.py
> +        training_params = read_conf(os.path.join(repodir, conf.training_conf))
Done.

2023-02-16 15:23 UTC, jeipollack commented on wf_psf/run.py
> +configs = read_stream(os.path.join(repodir, args.conffile))
Done.

2023-02-16 15:24 UTC, jeipollack commented
Hi @sfarrens , I pushed doc string style changes for `read_config.py`.

2023-02-16 15:33 UTC, jeipollack commented on wf_psf/training/train.py
> +        Dictionary storing optimiser parameters
yes, that was more a  note for myself since some of them are Tobias-defined variables :-)

2023-02-16 15:35 UTC, jeipollack commented on wf_psf/training/train.py
> +        Dictionary storing optimiser parameters
I will rename some of the variables

2023-02-17 11:10 UTC, jeipollack commented on wf_psf/training/train.py
> +        self.training_params = training_params.training
Done.

2023-02-17 11:10 UTC, jeipollack commented on wf_psf/training/train.py
> +    device_name
corrected

2023-02-17 11:10 UTC, jeipollack commented on wf_psf/training/train.py
> +    training_params: Recursive Namespace
I listed it as a `type` and noted below that is a Recursive Namespace object

2023-02-17 11:10 UTC, jeipollack commented on wf_psf/training/train.py
> +    workdir = os.getenv("HOME")
done

2023-02-20 12:11 UTC, jeipollack commented
Hi @sfarrens,  just want to send you a FYI that I did a few more changes in this branch more related to restructuring the package, but I did not push them.  Instead I decided to checkout a new branch to continue development there until this PR can be merged to the `dummy_main branch`.

2023-02-28 15:37 UTC, sfarrens approved these changes

2023-02-28 15:38 UTC, merged