Draft:Refactor psf models
CosmoStat/wf-psf pull request #55
Opened 2023-03-16 10:59 UTC by jeipollack

Major Changes in this PR:

- Reorganization of most of the modules to associated packages (`script_utils.py` will be made deleted in the future)
-

2023-03-22 10:52 UTC, sfarrens commented on wf_psf/data/training_preprocessing.py
> +    return dataset
I think you make this one line since you don't really need the `dataset` object.

2023-03-22 10:52 UTC, sfarrens commented on wf_psf/data/training_preprocessing.py
> +    or TrainingDataSetup
Is this something you want to keep in the docstring? If this is not something you plan to implement in this PR then perhaps it would be better as a developer note (i.e. `# Maybe rename ...`) or a `Todo` section.

2023-03-22 13:07 UTC, jeipollack commented on wf_psf/data/training_preprocessing.py
> +    return dataset
I decided to load the file explicitly during instantiation

2023-03-22 13:08 UTC, jeipollack commented on wf_psf/data/training_preprocessing.py
> +    or TrainingDataSetup
I forgot about this note. I removed it.

2023-03-22 14:56 UTC, jeipollack commented
lots of commits bc I forgot I need to use my personal access token to `git push` from JZ.

2023-03-24 13:06 UTC, sfarrens reviewed
Hi @jeipollack things are looking good. I opened a couple of minor threads. Some points to consider for `train.py`:

- The class method `train` is very long. I feel like a lot of these steps could be broken up into smaller "private" class methods.
- There are lots of `print` statements. Perhaps you could include a `verbose` option (which is `True` by default) in the UI and add `if verbose:` (or something to that effect) to these.

2023-03-24 13:06 UTC, sfarrens commented on wf_psf/data/training_preprocessing.py
> +      A class to handle test data for model validation.
```suggestion
    A class to handle test data for model validation.
```

2023-03-24 13:06 UTC, sfarrens commented on wf_psf/training/train.py
> +from wf_psf.psf_models import *
It's not good practice to use `import *` as it creates ambiguity as to where a given object (function, class, etc.) has come from. What I would propose instead is:

a. if there are only a few objects needed, to import them explicitly,
b. if there many objects needed, to import `psf_models` as an alias, e.g. `import wf_psf.psf_models as pm`

2023-03-28 13:54 UTC, jeipollack commented on wf_psf/training/train.py
> +from wf_psf.psf_models import *
this is only importing these modules:

__all__ = ['psf_models', 'psf_model_parametric', 'psf_model_semiparametric']

Do you still prefer I change?

2023-03-31 10:16 UTC, jeipollack commented
Hi @sfarrens , I am ready for you to complete your review of `train.py` . The refactoring resulted in changes to `configs/training_config.yaml` and additional attributes to `psf_models/psf_models_semiparametric.py`.

2023-04-03 12:54 UTC, jeipollack commented
PR Msg to test GH -> Slack.

2023-04-03 12:55 UTC, jeipollack commented
ah I won't receive a notification bc I sent it.

2023-04-05 08:00 UTC, sfarrens requested changes
Hi @jeipollack here is another round of comments. Overall things are looking good, but there are still some things that could be better abstracted (this can be looked at in a future PR). Also, make sure you check your data types to ensure they make sense.

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        super(TF_SemiParam_field, self).__init__()
This should work and is a bit cleaner, in particular if you decided to change the class name. 

```suggestion
        super().__init__()
```

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        and method to reinitialize PSF batch poly generator
I think this should just be a developer comment (i.e. starting with `#`) rather than part of the docstring if you wanted included in the PR.

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        input_positions:
Missing data type

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +
```suggestion
```

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +
```suggestion
```

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        )
This looks a bit messy to me. 

It doesn't need to be changed for this PR, but perhaps something we should come back to. Maybe you can add something like `# TODO: Clean up` (or something along those lines).

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        )
Same point here.

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +
Does this comment refer to the `S_mat_projected` object? It looks a bit lost.

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +    training_params: type
What is data type `type`?

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/psf_models/psf_model_semiparametric.py
> +)
Since most of these objects are only called once, it would probably be a lot leaner to do something like:

```python
from wf_psf.psf_models import psf_models as psfm
from wf_psf.psf_models import tf_layers as tfl
```

and then later something like e.g.:

```python
self.tf_poly_Z_field = tfl.TF_poly_Z_field(...)
```

etc.

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/training/train.py
> +from wf_psf.psf_models import *
Yes, I would argue we should never see `import *` in any part of the code.

2023-04-05 08:00 UTC, sfarrens commented on wf_psf/training/train.py
> +        multi_cycle_params: type
Data type `type` again?

2023-04-05 14:04 UTC, jeipollack commented on wf_psf/training/train.py
> +from wf_psf.psf_models import *
changed it.

2023-04-05 14:24 UTC, jeipollack commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        input_positions:
This function was written by @tobias-liaudat. It's not used in training but for metrics analysis.  It looks like it will accept as input a tensor in tensor flow float units. but, I will know when I test it further when refactoring the `metrics` package.

2023-04-05 14:26 UTC, jeipollack commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        )
I will make it a To Do.  As this module was written by Tobias, I was reluctant to review and refactor it as I didn't want to risk breaking sth.  We know it works as is.

2023-04-05 14:32 UTC, jeipollack commented on wf_psf/training/train.py
> +        multi_cycle_params: type
fixed.

2023-04-05 14:33 UTC, jeipollack commented on wf_psf/psf_models/psf_model_semiparametric.py
> +    training_params: type
Replaced with Recursive Namespace.

2023-04-05 14:33 UTC, jeipollack commented on wf_psf/psf_models/psf_model_semiparametric.py
> +
added it to the To Do list to figure out what this comment is about.

2023-04-05 14:33 UTC, jeipollack commented on wf_psf/psf_models/psf_model_semiparametric.py
> +        )
added to the To Do list

2023-04-06 10:49 UTC, jeipollack commented on wf_psf/psf_models/psf_model_semiparametric.py
> +)
Thanks! Done.

2023-04-06 11:42 UTC, jeipollack commented
hi @sfarrens I believe I've addressed all your comments and those by @tobias-liaudat on change some config variable names. Re-ran the code and all is good.

2023-04-07 11:00 UTC, sfarrens approved these changes

2023-04-07 11:00 UTC, merged