Refactor metrics
CosmoStat/wf-psf pull request #62
Opened 2023-05-10 14:49 UTC by jeipollack

This PR is more a refactoring of the training part of WaveDiff to remove redundant steps during metrics evaluation.  

Changes to be reviewed are in the following commits:

- https://github.com/CosmoStat/wf-psf/commit/40d5d0543f96fc1f787b3bfa3298157d1bd6e0b1
- https://github.com/CosmoStat/wf-psf/commit/d1a6e12510decea235b79d8803a77703d57d4778
- https://github.com/CosmoStat/wf-psf/commit/1f273b114b82dac63a58a7346ff920e9f9a0694d

I've performed other changes in the `tests` dir, `metrics_refactor.py`, etc. But, they're not ready for review, yet. So, this branch can't be merged.

2023-05-12 15:53 UTC, jeipollack commented
This last batch of commits can also be reviewed.

2023-05-12 16:03 UTC, jeipollack commented
one other comment, please don't delete branch bc I am still working on it

2023-05-15 13:25 UTC, sfarrens requested changes

2023-05-15 13:25 UTC, sfarrens commented on config/metrics_config.yaml
> +    sed_sigma: 0
I know this is outside the scope of the review, but these parameters appear to be defined twice.

2023-05-15 13:25 UTC, sfarrens commented on wf_psf/training/train.py
> +        training_handler._filepath_chkp_callback(checkpoint_dir, current_cycle),
If `_filepath_chkp_callback` is called outside of the scope of `training_handler` then it should probably not be a "hidden" attribute (i.e. no preceding `_`).

2023-05-15 13:25 UTC, sfarrens commented on wf_psf/training/train.py
> +from wf_psf.metrics.metrics_refactor import evaluate_model
1. Is `metrics_refactor` a temporary name while you are working on this module?
2. I don't see any calls to `evaluate_model` in this module, is it currently needed here?

2023-05-15 13:25 UTC, sfarrens commented on config/data_config.yaml
> +        max_wfe_rms: 0.1
I think GitHub is complaining because there is no empty line at the end of the file.

2023-05-15 13:27 UTC, sfarrens commented
Hi @jeipollack here are my first comments on this PR. I will run some tests and get back to you if I have any further comments.

2023-05-15 14:44 UTC, jeipollack commented on config/metrics_config.yaml
> +    sed_sigma: 0
yes, it is a duplication due to copying from training_config.yaml. I am still working on the metrics configs. so, this isn't the final version and not meant to be part of this PR.

2023-05-15 14:47 UTC, jeipollack commented on wf_psf/training/train.py
> +from wf_psf.metrics.metrics_refactor import evaluate_model
yes, it is temporary name.  And it was called but I decided to call it instead in `run.py`.  I will rm this import

2023-05-23 18:37 UTC, jeipollack commented
Everything is working as it should.  But, I see some possible configurations that could break the code or cause the user to not get the results they intended.

2023-05-24 09:42 UTC, jeipollack commented on wf_psf/training/train.py
> +        training_handler._filepath_chkp_callback(checkpoint_dir, current_cycle),
Fixed. I actually moved it outside of the class bc it's needed by the metrics module. I didn't see the need to make it a static method.

2023-05-24 09:44 UTC, jeipollack commented on config/data_config.yaml
> +        max_wfe_rms: 0.1
sorry I don't understand. how do you know it's complaining?

2023-05-24 09:50 UTC, jeipollack commented
The scope of this PR is to check the UI with the refactored metrics option.  I know the name `metrics_refactor.py` is not a good one, but all the commands in there were in `script_utils.py`.   The `metrics_refactor.py` is like an interface module for the `metrics.py` module, so it's not meant to override it.  Should I change the name to `metrics_interface.py`?

2023-05-24 12:04 UTC, jeipollack commented
To add, I realised that `run.py` has a bit more complicated because of the different config options.  I am thinking about how to make it cleaner/less complicated using factory methods.

2023-05-24 14:31 UTC, sfarrens commented on config/data_config.yaml
> +        max_wfe_rms: 0.1
I am pretty sure that's what the red circle with the minus means.
...............👇
![image](https://github.com/CosmoStat/wf-psf/assets/6851839/8f87b59a-e294-4637-a744-65fd92167b22)

2023-05-24 15:50 UTC, sfarrens commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
[STESS TEST] Providing an invalid path/filename or data type for any of the conf files provides an output log without any error information. The error can only be retrieved from the stderr.

2023-05-24 15:50 UTC, sfarrens commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
[STRESS TEST] Providing an invalid key to `configs.yml` (e.g. `xetrics_conf` instead of `metrics_conf`) does not raise any error. The code simply runs as if `metrics_conf` was not provided. This doesn't break anything, but it may be worth adding a check that only valid keys have been provided.

2023-05-24 15:50 UTC, sfarrens commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
[STRESS TEST] The config file is read in from a path relative to the repository directory. This only makes sense if you assume that the user will only ever use config files already provided in the repo. Otherwise, defining an absolute path to the config files can get complicated if `repodir` is anything other than `.`.

2023-05-24 15:50 UTC, sfarrens commented
> The scope of this PR is to check the UI with the refactored metrics option. I know the name `metrics_refactor.py` is not a good one, but all the commands in there were in `script_utils.py`. The `metrics_refactor.py` is like an interface module for the `metrics.py` module, so it's not meant to override it. Should I change the name to `metrics_interface.py`?

Yes, I think that would make more sense.

2023-05-24 15:51 UTC, sfarrens commented
@jeipollack I have added some feedback following some basic stress tests. You don't have to implement the changes in this PR, but I do think these points will be need to be addressed at some point.

2023-05-25 10:39 UTC, jeipollack commented on config/data_config.yaml
> +        max_wfe_rms: 0.1
I see. I though it was shifted by a row not column :). Fixed.

2023-05-25 14:20 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
sorry does the data type have to do with the contents of the file or the file extension?

2023-05-25 14:20 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
I ask bc if it's the file extension then the error would be FileNotFound

2023-05-25 14:21 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
could you provide me an example of the test cases you used? (this is what the automatic testing program in Google wouldn't reveal :-) )

2023-05-25 15:44 UTC, jeipollack commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
I corrected this with an exception

2023-05-26 09:32 UTC, jeipollack commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
same is true about the data sets.

2023-05-26 09:32 UTC, jeipollack commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
I'm thinking what to do.

2023-05-26 09:34 UTC, sfarrens commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
Why not make the config file argument a full path in the first place?

2023-05-26 09:38 UTC, sfarrens commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
Yes, sorry. What I meant is that if you did something like:

```yaml
data_conf: config/data_config.yaml
training_conf: config/training_config.yaml
metrics_conf: null
```

Where obviously you would expect an error for the invalid data type for the key `metrics_conf` this error only appears in the stderr and not in the run log.

2023-05-26 09:44 UTC, jeipollack commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
I am thinking to change it in such way, but using the path to the config provided at runtime.

2023-05-26 10:34 UTC, jeipollack commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
Ii changed it to full path for config file.  In the `data_config.yaml` file, I added an entry `data_dir` in both the `training:` and `test:` sections to specify the respective paths to train and test data in case they're stored in separate directories.

2023-05-26 10:35 UTC, jeipollack commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
Just to add. the user needs only specify the name of the config file.

2023-05-26 10:50 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
Hmm...not sure how to interpret this.  If the user entered `null` I would think it's because they only want to train the model. So, why should there be an error?

2023-05-26 10:53 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
To test this quicker, I ran with the configuration below.  It throws a TypeError exception with the warning Training & Metrics run is skipped but carries on with metrics evaluation.

```
---
  data_conf: data_config.yaml
  training_conf: null
  metrics_conf: metrics_config.yaml
```

2023-05-26 10:53 UTC, sfarrens commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
That's a valid point, but at it stands this will raise an error because it is looking for a path following the keywords. You could make `null` a valid data type, but what if someone puts e.g. `3`, the error should be logged so that the user know what went wrong with their config file settings.

2023-05-26 11:02 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
if someone makes a typo in providing the config file name then an exception is thrown and output to log.  Would that be sufficient?

2023-05-26 11:04 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
sorry I didn't refresh and saw your message above.  I will edit the code for this type of error.

2023-05-26 11:38 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
okay I added Exception Handling for `TypeError` & `FileNotFoundError`.   Program should exist for those cases. Exception is `Null`.

2023-05-26 11:39 UTC, jeipollack commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
(I kinda like writing this type of code) :D

2023-05-26 17:29 UTC, jeipollack commented
Latest modification (untested full on JZ) is to store outputs in a unique dir `wf-outputs-YearMonthDayHourMin`.

```
wf-outputs
├── wf-outputs-202305261923
│   ├── checkpoint
│   ├── log-files
│   ├── metrics
│   ├── optim-hist
│   └── plots
├── wf-outputs-202305261925
│   ├── checkpoint
│   ├── log-files
│   │   └── wf-psf_202305261925.log
│   ├── metrics
│   ├── optim-hist
│   └── plots
└── wf-outputs-202305261926
    ├── checkpoint
    ├── log-files
    │   └── wf-psf_202305261926.log
    ├── metrics
    ├── optim-hist
    └── plots
```

2023-05-27 17:32 UTC, jeipollack commented
Okay, I think I've implemented some enough keys changes to close out this PR.

2023-05-31 10:37 UTC, sfarrens commented on wf_psf/utils/io.py
> +            + self._parent_output_dir
You are missing a `"/"` here. As it stands this raises an error as the directory cannot be created. 

Perhaps it would be safer/cleaner to use `os.path.join`.

2023-05-31 10:50 UTC, sfarrens commented on wf_psf/run.py
> +            logger.info(metrics_params.metrics)
Looks good now, good job!

2023-05-31 12:35 UTC, sfarrens commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
This does not appear to be fixed, at least not as I expected. Misspelling the keys `training_conf` or `metrics_conf` is simply ignored.

2023-05-31 13:59 UTC, sfarrens commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
OK, with the [latest commit](https://github.com/CosmoStat/wf-psf/pull/62/commits/70f1572d9616f619b74d6477e39d255391c33745) this is workable. I think we may want to revisit the error messages and exception handling in a follow up PR, but let's leave it for now.

2023-05-31 14:57 UTC, sfarrens commented on wf_psf/run.py
>      configs = read_stream(os.path.join(args.repodir, args.conffile))
OK, this seems to be mostly fixed. I think the only thing that is missing is an exception that is raised if the user tries to provide a path to `configs.yaml`, and it should be clearly specified that all the config files will have to be stored in the same location. Again, I think this can be addressed in a follow up PR.

2023-05-31 15:00 UTC, sfarrens approved these changes

2023-05-31 15:01 UTC, sfarrens commented
OK @jeipollack I am merging this PR. Good job! 👏

2023-05-31 15:01 UTC, merged