Draft:Feature documentation
CosmoStat/wf-psf pull request #80
Opened 2023-10-13 13:08 UTC by jeipollack

testing

2023-10-31 13:33 UTC, sfarrens requested changes

2023-10-31 13:33 UTC, sfarrens commented on .github/workflows/ci.yml
I think you need to pull/rebase from dummy_main as I don't think you want to merge these changes to the `ci.yml`.

2023-10-31 13:33 UTC, sfarrens commented on docs/source/installation.md
> +WaveDiff is a software written in the programming language Python and uses the [TensorFlow](https://www.tensorflow.org) framework to train and evaluate the model parameters of the PSF model. Therefor
```suggestion
WaveDiff is a software written in Python and uses the [TensorFlow](https://www.tensorflow.org) framework to train and evaluate the model parameters of the PSF model. Therefore, it is advisable to run the WaveDiff software on machines equipped with a GPU.  
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/installation.md
> +Note: You may want to set up a dedicated Python environment for running WaveDiff using [Conda](https://docs.conda.io/en/latest/).  You can use the minimal installer [Miniconda](https://docs.conda.io/
```suggestion
Note: You may want to set up a dedicated Python environment for running WaveDiff using e.g. [Conda](https://docs.conda.io/en/latest/).  You can use the minimal installer [Miniconda](https://docs.conda.io/projects/miniconda/en/latest/) to set up the environment in which we run the command below to install the subset of packages needed for running WaveDiff.
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/basic_execution.md
> +  --repodir REPODIR, -r REPODIR
Why do we need to specify this?

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +The key `model_params` defines the model parameters for the type of PSF model to be trained.  The identifier of the type of PSF model to be trained is stored in `model_name`.  While the several model
```suggestion
The key `model_params` defines the model parameters for the type of PSF model to be trained.  The identifier of the type of PSF model to be trained is stored in `model_name`.  While the model options are listed in the key description, for now only the `poly` model is implemented. 
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +The [metrics_config.yaml](https://github.com/CosmoStat/wf-psf/blob/dummy_main/config/metrics_config.yaml) file stores the configuration parameters for the WaveDiff pipeline to carry out a set of comp
```suggestion
The [metrics_config.yaml](https://github.com/CosmoStat/wf-psf/blob/dummy_main/config/metrics_config.yaml) file stores the configuration parameters for the WaveDiff pipeline to carry out a set of computations for the four metrics listed in the table below on a trained PSF model for the input training and test data sets, as applied in {cite:t}`Liaudat:23`.
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +As stated in the previous section, the `metrics` evaluation pipeline can be executed subsequently after the completion of the `training` routine to evaluate the trained PSF model.  It can also be lau
```suggestion
As stated in the previous section, the `metrics` evaluation pipeline can be executed subsequently after the completion of the `training` routine to evaluate the trained PSF model.  It can also be launched independently to compute the metrics of a previously trained model.  This is done by setting the value of the parameter `trained_model_path` to the absolute path of the parent directory containing the output files of the model.  This is the directory with the naming convention: `wf-outputs-timestamp` (see this {ref}`example of the run output directory<wf-outputs>`).  The user must then provide as a value to `trained_model_config` the subdirectory path to the training configuration file, e.g.: `config/train_config.yaml`. Below we show an example of this for the case where a user wants to run metrics evaluation of the full PSF model of a pre-trained PSF model saved in the directory `wf-outputs-202310161536`. 
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +The option to generate plots of the metric evaluation results is provided by setting the value of the parameter `plotting_config` to the name of the [plotting configuration](plotting_config) file, ex
```suggestion
The option to generate plots of the metric evaluation results is provided by setting the value of the parameter `plotting_config` to the name of the [plotting configuration](plotting_config) file, e.g.: `plotting_config.yaml`.  This will trigger WaveDiff's plotting pipeline to produce plots after completion of the metrics evaluation pipeline.  If the field is left empty, no plots are generated. 
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +The `metrics` package is run using [TensorFlow](https://www.tensorflow.org) to reconstruct the PSF model and evaluate the various metrics. The `metrics_hparams` key contains a couple usual machine le
```suggestion
The `metrics` package is run using [TensorFlow](https://www.tensorflow.org) to reconstruct the PSF model and evaluate the various metrics. The `metrics_hparams` key contains some standard machine learning parameters such as the `batch_size` as well as additional parameters like `output_dim` to define the dimension of the output pixel postage stamp, etc.  
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +As nearly all of the specific plotting parameters are pre-coded by default, the parameters of the `plotting_config` file are to enable the option to plot multiple metrics from other trained PSF model
I am not sure I get what "the specific plotting parameters are pre-coded" means in practice. Can you explain?

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +As nearly all of the specific plotting parameters are pre-coded by default, the parameters of the `plotting_config` file are to enable the option to plot multiple metrics from other trained PSF model
```suggestion
As nearly all of the specific plotting parameters are pre-coded by default, the parameters of the `plotting_config` file are to enable the option to plot multiple metrics from other trained PSF models for comparison. The `metrics_output_path` is the path to the parent directory containing the subdirectories of all runs (see example below).
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +Each training task is run sequentially and independently of the other.  All of the results are stored in the same `wf-outputs-<timestamp>` directory as shown in the example below.
```suggestion
Each training task is run sequentially and independently of the others.  All of the results are stored in the same `wf-outputs-<timestamp>` directory as shown in the example below.
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +Likewise, to do metrics evaluation and generate plots for each training run as shown above the corresponding names of the `metrics_config.yaml` and `plotting_config.yaml` file need to be provided as
```suggestion
Likewise, to perform a metrics evaluation and generate plots for each training run, as shown above, the corresponding names of the `metrics_config.yaml` and `plotting_config.yaml` files need to be provided as values to the corresponding `{metrics|plotting}_config` parameters in `training_config_{id}.yaml` and `metrics_config.yaml`, respectively. The same `metrics_config.yaml` and `plotting_config.yaml` files can be used for each `training_config_{id}.yaml` file.  Below is an example of the `config` tree structure for a `training` + `metrics` + `plotting` run:
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +Note, in this version of WaveDiff the plots are produced only per each metric per trained model.  To produce a single plot displaying the metrics for each trained model, the user must do so in a diff
I don't understand what "the plots are produced only per each metric per trained model" means.

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +Note, in this version of WaveDiff the plots are produced only per each metric per trained model.  To produce a single plot displaying the metrics for each trained model, the user must do so in a diff
```suggestion
Note, in this version of WaveDiff the plots are produced only per each metric per trained model.  To produce a single plot displaying the metrics for each trained model, the user must do so in a different run following the steps defined in [Plot Configuration](plotting_config). The next upgrade to WaveDiff will feature the option to produce independent metrics plots per trained model and/or a single master plot for each metric comparing the respective metric results for all trained models.
```

2023-10-31 13:33 UTC, sfarrens commented on docs/source/configuration.md
> +The master configuration file can include a combination of the three pipeline tasks, i.e. training, metrics and plotting, to do independent tasks like train a new PSF model, compute the metrics of pr
```suggestion
The master configuration file can include a combination of the three pipeline tasks, i.e. training, metrics and plotting, to do independent tasks like train a new PSF model, compute the metrics of a  pre-trained PSF model, or produce plots for a selection of pre-computed metrics. While currently WaveDiff executes these jobs sequentially on a single GPU, the future plan is to distribute these tasks in parallel across multiple GPUs to accelerate the computation.
```

2023-10-31 13:33 UTC, sfarrens commented on src/wf_psf/tests/data/validation/main_random_seed/checkpoint/checkpoint
Do we need to save the checkpoints?

2023-10-31 15:24 UTC, jeipollack commented on .github/workflows/ci.yml
Rebasing turned out to be rather complicated with a lot of conflicts. It seems I had duplicated commits (or changes).  But, if I ran a `git log feature_documentation..dummy_main` I saw just a few commits were missing from dummy_main into the feature_documentation branch. So, I just did a `git merge` to add these missing commits to the feature_documentation branch. However, the [specific merge commit ](https://github.com/CosmoStat/wf-psf/commit/87e78c3946549b3d8556d3bcc702d500925765a1)shows nothing.  But, I see the missing commits in the log now.  I have to review better `git rebase` versus `git merge`.

2023-10-31 15:29 UTC, jeipollack commented on docs/source/basic_execution.md
> +  --repodir REPODIR, -r REPODIR
do you mean why am I including it in the documentation?

2023-10-31 15:55 UTC, jeipollack commented on docs/source/basic_execution.md
> +  --repodir REPODIR, -r REPODIR
While the code can be called from anywhere, the dataset files and SEDs are in sub-directories inside the repo dir.  I guess it could be specified in the config file.  I will think about it some more.

2023-10-31 16:09 UTC, jeipollack commented on src/wf_psf/tests/data/validation/main_random_seed/checkpoint/checkpoint
yes, bc I am validating them in the end-to-end, since Tobias wants the option to run metrics either on a `final model` or one of the `checkpoints`.

2023-11-06 11:32 UTC, jeipollack commented on docs/source/basic_execution.md
> +  --repodir REPODIR, -r REPODIR
The batch job script executes the command `cd $WORK/wf-psf` before running WaveDiff to put us at the directory level.  For the datasets, I see only the relative path is specified.  It does appear that the repodir arg is only used to retrieve the logging config file, but this could be changed in the next quick update. Or shall I modify now?

2023-11-06 14:30 UTC, sfarrens commented on docs/source/basic_execution.md
> +  --repodir REPODIR, -r REPODIR
No, it's fine to update this in a later PR. Please just make an issue so that we don't forget.

2023-11-06 14:36 UTC, sfarrens commented on .github/workflows/ci.yml
> +  workflow_dispatch:
I guess here you would like to make it so the CI tests can be triggered manually in addition to the automatic PR trigger? If so, have you tested that this works on a fork? I only asked because I have never combined manual and automatic triggers for a given workflow before.

2023-11-06 14:39 UTC, sfarrens commented
Hi @jeipollack there are still some unresolved threads that perhaps you missed because GitHub hides them by default. Where is says "5 hidden conversations" above click on "Load more..." to see everything. 

I opened one last thread on the `ci.yml` file. I think we can merge once all of these threads are resolved.

2023-11-06 16:34 UTC, jeipollack commented on docs/source/configuration.md
> +As nearly all of the specific plotting parameters are pre-coded by default, the parameters of the `plotting_config` file are to enable the option to plot multiple metrics from other trained PSF model
corrected.

2023-11-06 16:35 UTC, jeipollack commented on docs/source/configuration.md
> +The `metrics` package is run using [TensorFlow](https://www.tensorflow.org) to reconstruct the PSF model and evaluate the various metrics. The `metrics_hparams` key contains a couple usual machine le
changed using your suggestion.

2023-11-06 16:35 UTC, jeipollack commented on docs/source/configuration.md
> +The option to generate plots of the metric evaluation results is provided by setting the value of the parameter `plotting_config` to the name of the [plotting configuration](plotting_config) file, ex
changed to e.g.

2023-11-06 16:35 UTC, jeipollack commented on docs/source/configuration.md
> +As stated in the previous section, the `metrics` evaluation pipeline can be executed subsequently after the completion of the `training` routine to evaluate the trained PSF model.  It can also be lau
changed to e.g.

2023-11-06 16:37 UTC, jeipollack commented on .github/workflows/ci.yml
> +  workflow_dispatch:
Removed the workflow dispatch trigger.

2023-11-06 16:38 UTC, jeipollack commented on docs/source/configuration.md
> +As nearly all of the specific plotting parameters are pre-coded by default, the parameters of the `plotting_config` file are to enable the option to plot multiple metrics from other trained PSF model
Pre-coded means that the plotting parameters such as fig-size, subplots, legend, etc are defined directly in the plotting script.

2023-11-07 13:12 UTC, sfarrens approved these changes

2023-11-07 13:12 UTC, merged